name = "Darwin"
uuid = "2164de58-03dd-423f-8511-b34e3703ca01"
authors = ["Philipp Gabler <phipsgabler@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LearningStrategies = "4e8a8231-0ba9-591b-8620-81c6740d7791"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
